version: '3'

services:
  database:
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_EXTENSIONS: uuid-ossp
      PGDATA: /data/postgres

    volumes:
      - postgres_data:/var/lib/postgres
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - back_end
      
  app:
    build: .
    ports:
      - '81:3000'
    networks:
      - back_end
    command: npm run dev
    volumes:
      - .:/src/
      - nodemodules:/src/node_modules
    links:
      - database
    depends_on:
      - database  

  nginx:
    build: ./nginx
    ports:
      - '8080:80'
    depends_on:
      - app
    networks:
      - back_end
  
        
networks:
  back_end:
    driver: bridge

volumes:
  postgres_data:
  nodemodules: {}
